backend:
  # Use netlify identity as backend
  name: git-gateway
  branch: main
  ### enable below lines for github integration ###
  # name: github
  repo: cyrilf/dandahughes
media_folder: "src/static/img"
public_folder: "/static/img"
show_preview_links: true
site_url: https://dandahughes.com

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
# publish_mode: editorial_workflow
collections:
  - label: "Content"
    name: "content"
    files:
      - label: "Content"
        name: "content"
        editor:
          preview: false
        file: "src/_data/dataContent.yaml"
        fields:
          - { label: Seo Title, name: seoTitle, widget: string }
          - { label: Seo Description, name: seoDescription, widget: string }
          - { label: Intro Title, name: introTitle, widget: string }
          - { label: Intro Text, name: introText, widget: text }
          - { label: Intro Image, name: introImg, widget: image }
          - { label: About Title, name: aboutTitle, widget: string }
          - { label: About Text, name: aboutText, widget: text }
          - { label: About Image, name: aboutImg, widget: image }
          - { label: About Image Title, name: aboutImgTitle, widget: string }
          - { label: About Image Text, name: aboutImgText, widget: text }
          - { label: Music Title, name: musicTitle, widget: string }
          - { label: Music Text, name: musicText, widget: text }
          - { label: Music Button, name: musicButton, widget: string }
          - { label: Music Button Link, name: musicButtonLink, widget: string }
      - label: "Social links"
        name: "social"
        file: "src/_data/social.yaml"
        fields:
          - label: Links
            label_singular: Link
            name: items
            widget: list
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Link, name: link, widget: string }
              - { label: Icon, name: icon, widget: string }
              - { label: Color name, name: colorName, widget: string }
      - label: "Albums"
        name: "albums"
        file: "src/_data/albums.yaml"
        fields:
          - label: Albums
            label_singular: Album
            name: items
            widget: list
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Cover, name: cover, widget: image }
              - { label: Description, name: description, widget: text }
              - { label: Link, name: link, widget: string }
  - label: "Settings"
    name: "settings"
    editor:
      preview: false
    files:
      - label: "Navigation"
        name: "items"
        file: "src/_data/navigation.yaml"
        fields:
          - label: Nav Items
            name: items
            widget: list
            fields:
              - { label: Title, name: text, widget: string }
              - { label: URL, name: url, widget: string }
      - label: "Meta Settings"
        name: "settings"
        file: "src/_data/settings.yaml"
        fields:
          - { label: Name, name: name, widget: string }
          - { label: Author, name: author, widget: string }
          - { label: URL, name: url, widget: string }
